# Generated by Django 3.1.2 on 2020-10-26 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('memory', models.CharField(max_length=30)),
                ('cpu', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MySQLSchema',
            fields=[
                ('gmt_update', models.DateTimeField(auto_now=True, null=True)),
                ('gmt_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('port', models.IntegerField()),
                ('schema', models.CharField(max_length=64)),
                ('role', models.CharField(choices=[('master', 'master'), ('slave', 'slave')], max_length=64)),
                ('status', models.EmailField(default='online', max_length=64)),
                ('host_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta_manage.host')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
