# Generated by Django 3.1.2 on 2020-10-26 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta_manage', '0002_auto_20201026_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqlschema',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meta_manage.host'),
        ),
        migrations.AlterField(
            model_name='mysqlschema',
            name='host_ip',
            field=models.GenericIPAddressField(),
        ),
    ]
