# Generated by Django 3.0.6 on 2020-09-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='用户名', max_length=64)),
                ('content', models.TextField(help_text='内容', max_length=65535)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True)),
                ('deleted', models.BooleanField(default=False, help_text='是否被删除')),
                ('email', models.EmailField(help_text='邮箱', max_length=254, null=True)),
                ('ip', models.GenericIPAddressField(help_text='ip地址', null=True)),
                ('null_bool', models.NullBooleanField()),
                ('uuid', models.UUIDField(null=True)),
            ],
        ),
    ]
