# Generated by Django 3.0.6 on 2020-09-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='username',
            field=models.CharField(db_index=True, help_text='用户名', max_length=64),
        ),
    ]
