# Generated by Django 3.0.6 on 2020-09-08 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200908_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, help_text='用户名', max_length=64)),
                ('content', models.TextField(help_text='内容', max_length=65535)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True)),
                ('deleted', models.BooleanField(default=False, help_text='是否被删除')),
                ('email', models.EmailField(help_text='邮箱', max_length=254, null=True)),
                ('ip', models.GenericIPAddressField(help_text='ip地址', null=True)),
                ('null_bool', models.NullBooleanField()),
                ('uuid', models.UUIDField(null=True)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Reporter')),
            ],
        ),
    ]
