# Generated by Django 3.0.6 on 2020-09-10 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_place_restaurant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['email']},
        ),
    ]
