# Generated by Django 2.0.5 on 2019-09-19 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20190919_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='provice',
            new_name='province',
        ),
    ]
