---
- hosts: mysql-master
  become: True
  vars:
    mysql_data_dir_base: /data/mysql/
    mysql_port: 3306
    mysql_base_dir: /opt/mysql-8.0.16-linux-glibc2.12-x86_64/
    install_packages:
      - vim
      - unzip
      - libaio
      - libaio-devel
      - numactl-devel
      - perl-Data-Dumper 
  tasks:
    - name: install packages
      # yum 模块
      package:
        name: "{{ install_packages }}"
        state: present

    - name: create mysql group
      # group 模块，创建mysql用户组为 mysql 
      group:
        name: mysql
        state: present
 
    - name: create mysql user
      # user 模块，创建mysql用户为 mysql, 所属组为 mysql，并且设置没有权限登录
      user:
        name: mysql
        group: mysql
        state: present
        shell: /sbin/nologin

    #- name: scp the mysql installer
    #  unarchive:
    #    src: mysql-8.0.16-linux-glibc2.12-x86_64.zip
    #    dest: /opt/
    #    owner: mysql
    #    group: mysql

    - name: Add mysql bin dir to $PATH.
      # copy 模块, 
      copy:
        dest: /etc/profile.d/mysql-path.sh   # 这个 mysql-path.sh 文件从哪里来的
        content: 'PATH=$PATH:{{ mysql_base_dir }}bin'

    - name: mkdir data base dir
      # file 模块，创建文件/目录，并且设置所属用户和所属组为 mysql
      file:
        path: "{{ mysql_data_dir_base }}{{ mysql_port }}" 
        state: directory
        owner: mysql
        group: mysql

    - name: template my.cnf
      # 引用模板
      template:
        src: my.cnf.tmpl
        dest: "/etc/my.{{mysql_port}}.cnf"
        owner: mysql
        group: mysql
        backup: yes
