---
- hosts: mysql-master
  # 我们在playbook的最前面添加 become: True, 整个任务就会以root执行
  become: True
  vars:
  
    # MySQL 根目录
    mysql_root_directory: /home/mysql/  
    
    # MySQL数据目录
    mysql_data_dir: /data
    
    mysql_port: 3306
    
    # MySQL二进制包的路径
    mysql_base_dir: /opt/mysql-8.0.16-linux-glibc2.12-x86_64/
    install_packages:
      - vim
      - unzip
  tasks:
    #- name: install packages
      # yum 模块
      #package:
        #name: "{{ install_packages }}"
        #state: present
    
    
    - name: check mysqld is exist
      shell: "netstat -tunlp|grep 3306 | wc -l"
      register: r
      
    - debug:
        var: r
        


[root@localhost data]# netstat -tunlp|grep 3306 | wc -l
0

[vagrant@localhost ansible]$ ansible-playbook mysql_debug3.yml 
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details

PLAY [mysql-master] ****************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************************************************************
ok: [192.168.0.45]

TASK [check mysqld is exist] *******************************************************************************************************************************************************************************************************************
changed: [192.168.0.45]

TASK [debug] ***********************************************************************************************************************************************************************************************************************************
ok: [192.168.0.45] => {
    "r": {
        "changed": true,
        "cmd": "netstat -tunlp|grep 3306 | wc -l",
        "delta": "0:00:00.009197",
        "end": "2020-12-07 04:03:34.060587",
        "failed": false,
        "rc": 0,
        "start": "2020-12-07 04:03:34.051390",
        "stderr": "",
        "stderr_lines": [],
        "stdout": "0",
        "stdout_lines": [
            "0"
        ]
    }
}

PLAY RECAP *************************************************************************************************************************************************************************************************************************************
192.168.0.45               : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  




----------------------------------------------------------------------------------------------------------------------

[root@localhost data]# netstat -tunlp|grep 3306 | wc -l
1
[vagrant@localhost ansible]$ ansible-playbook mysql_debug3.yml 
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details

PLAY [mysql-master] ****************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************************************************************
ok: [192.168.0.45]

TASK [check mysqld is exist] *******************************************************************************************************************************************************************************************************************
changed: [192.168.0.45]

TASK [debug] ***********************************************************************************************************************************************************************************************************************************
ok: [192.168.0.45] => {
    "r": {
        "changed": true,
        "cmd": "netstat -tunlp|grep 3306 | wc -l",
        "delta": "0:00:00.008360",
        "end": "2020-12-07 04:06:10.039509",
        "failed": false,
        "rc": 0,
        "start": "2020-12-07 04:06:10.031149",
        "stderr": "",
        "stderr_lines": [],
        "stdout": "1",
        "stdout_lines": [
            "1"
        ]
    }
}

PLAY RECAP *************************************************************************************************************************************************************************************************************************************
192.168.0.45               : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   




