# Generated by Django 3.1.3 on 2021-01-13 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta_manage', '0004_schematest5'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchemaTest5',
        ),
    ]
