# Generated by Django 3.1.3 on 2021-01-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_manage', '0005_delete_schematest5'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqlschema',
            name='instance_name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
