# Generated by Django 3.1.3 on 2021-01-18 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meta_manage', '0007_auto_20210118_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='gmt_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mysqlschema',
            name='gmt_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
