# Generated by Django 2.0.5 on 2019-09-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190919_1706'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Provice',
            new_name='Province',
        ),
    ]
