# Generated by Django 3.1.3 on 2021-01-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slowquery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slowqueryhistory',
            name='db_max',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
