# Generated by Django 3.1.3 on 2021-01-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slowquery', '0002_auto_20210118_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slowqueryhistory',
            name='db_max',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
