# Generated by Django 3.1.3 on 2021-01-26 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta_manage', '0010_efgmodel'),
        ('slowquery', '0003_auto_20210118_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmSettingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_alarm', models.BooleanField(default=False)),
                ('sql_print_hash', models.CharField(max_length=128)),
                ('sql_print', models.TextField()),
                ('query_time', models.FloatField()),
                ('query_count', models.IntegerField()),
                ('delete', models.BooleanField(default=False)),
                ('schema', models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='meta_manage.mysqlschema')),
            ],
            options={
                'db_table': 'alermsetting',
            },
        ),
    ]
