---
- hosts: mysql-master
  # 我们在playbook的最前面添加 become: True, 整个任务就会以root执行
  become: True
  vars:
  
    # MySQL 根目录
    mysql_root_directory: /home/mysql/  
    
    # MySQL数据目录
    mysql_data_dir: /data
    
    mysql_port: 3306
    
    # MySQL二进制包的路径
    mysql_base_dir: /opt/mysql-8.0.16-linux-glibc2.12-x86_64/
    install_packages:
      - vim
      - unzip
  tasks:
    - name: install packages
      # yum 模块
      package:
        name: "{{ install_packages }}"
        state: present
    
    - name: check initialize
      shell: "ls {{ mysql_root_directory }}{{ mysql_port }}{{ mysql_data_dir }} | wc -l"
      register: data_dir_count
      tags:
        - checkInitialize
        
    - name: debug
      debug: var=data_dir_count
      when: data_dir_count.rc == 0 and data_dir_count.stdout != "0"
      tags:
        - checkInitialize   
        
        
    # ansible-playbook mysql_debug.yml --tags checkInitialize
    
  
 
[root@localhost data]# ls /home/mysql/3306/data | wc -l
13
[root@localhost data]# ll
total 122968
srwxrwxrwx 1 mysql mysql        0 Dec  7 02:50 3306.sock
-rw------- 1 mysql mysql        5 Dec  7 02:50 3306.sock.lock
-rw-r----- 1 mysql mysql       56 Dec  3 03:52 auto.cnf
-rw-r----- 1 mysql mysql    44327 Dec  7 02:50 error.log
-rw-r----- 1 mysql mysql      361 Dec  7 02:49 ib_buffer_pool
-rw-r----- 1 mysql mysql 12582912 Dec  7 02:50 ibdata1
-rw-r----- 1 mysql mysql 50331648 Dec  7 02:50 ib_logfile0
-rw-r----- 1 mysql mysql 50331648 Dec  3 03:52 ib_logfile1
-rw-r----- 1 mysql mysql 12582912 Dec  7 02:50 ibtmp1
-rw-r----- 1 mysql mysql        5 Dec  7 02:50 localhost.pid
drwxr-x--- 2 mysql mysql     4096 Dec  3 03:52 mysql
drwxr-x--- 2 mysql mysql     8192 Dec  3 03:52 performance_schema
drwxr-x--- 2 mysql mysql     8192 Dec  3 03:52 sys
 
[vagrant@localhost ansible]$ ansible-playbook mysql_debug.yml --tags checkInitialize
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details

PLAY [mysql-master] ****************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************************************************************
ok: [192.168.0.45]

TASK [check initialize] ************************************************************************************************************************************************************************************************************************
changed: [192.168.0.45]

TASK [debug] ***********************************************************************************************************************************************************************************************************************************
ok: [192.168.0.45] => {
    "data_dir_count": {
        "changed": true,
        "cmd": "ls /home/mysql/3306/data | wc -l",
        "delta": "0:00:00.014949",
        "end": "2020-12-07 03:01:49.838179",
        "failed": false,
        "rc": 0,
        "start": "2020-12-07 03:01:49.823230",
        "stderr": "",
        "stderr_lines": [],
        "stdout": "13",
        "stdout_lines": [
            "13"
        ]
    }
}

PLAY RECAP *************************************************************************************************************************************************************************************************************************************
192.168.0.45               : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   


----------------------------------------------------------------------------------------------------------------------


[root@localhost logs]#  ls /home/mysql/3306/data | wc -l
0


[vagrant@localhost ansible]$ ansible-playbook mysql_debug.yml --tags checkInitialize
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details

PLAY [mysql-master] ****************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************************************************************
ok: [192.168.0.45]

TASK [check initialize] ************************************************************************************************************************************************************************************************************************
changed: [192.168.0.45]

TASK [debug] ***********************************************************************************************************************************************************************************************************************************
skipping: [192.168.0.45]

PLAY RECAP *************************************************************************************************************************************************************************************************************************************
192.168.0.45               : ok=2    changed=1    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   



